webtalk_init -webtalk_dir D:/Aghilan/Amrita/Project_phase_2/hardware_trojan/Vivado projects/uart_with_hw_trojan_testing/uart_with_hw_trojan_testing.sim/sim_1/behav/xsim/xsim.dir/hw_troj_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sun Jun 30 20:33:19 2024" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "af938fad-9aa5-4fa4-8952-34800b6cddc3" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "0f7a7e080d28403e81cb0541b18aa6b6" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "46" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 5 4600H with Radeon Graphics         " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2994 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "2" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "12179555 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.70_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "15476_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1946850516 -regid "" -xml D:/Aghilan/Amrita/Project_phase_2/hardware_trojan/Vivado projects/uart_with_hw_trojan_testing/uart_with_hw_trojan_testing.sim/sim_1/behav/xsim/xsim.dir/hw_troj_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/Aghilan/Amrita/Project_phase_2/hardware_trojan/Vivado projects/uart_with_hw_trojan_testing/uart_with_hw_trojan_testing.sim/sim_1/behav/xsim/xsim.dir/hw_troj_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/Aghilan/Amrita/Project_phase_2/hardware_trojan/Vivado projects/uart_with_hw_trojan_testing/uart_with_hw_trojan_testing.sim/sim_1/behav/xsim/xsim.dir/hw_troj_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
