webtalk_init -webtalk_dir E:/Aghilan/Amrita/Sem - VI/Open Lab/Vivado projects/uart_rx/uart_rx.sim/sim_1/behav/xsim/xsim.dir/tb_uart_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Feb 28 13:56:31 2023" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "9342491d-3d93-4d63-bef0-bf0323e06acc" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "8e87574559384eb2a534d5ec3150c647" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "12" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 5 4600H with Radeon Graphics         " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2994 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "2" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "7.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "73911880 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "2.37_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "14740_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3107508913 -regid "" -xml E:/Aghilan/Amrita/Sem - VI/Open Lab/Vivado projects/uart_rx/uart_rx.sim/sim_1/behav/xsim/xsim.dir/tb_uart_behav/webtalk/usage_statistics_ext_xsim.xml -html E:/Aghilan/Amrita/Sem - VI/Open Lab/Vivado projects/uart_rx/uart_rx.sim/sim_1/behav/xsim/xsim.dir/tb_uart_behav/webtalk/usage_statistics_ext_xsim.html -wdm E:/Aghilan/Amrita/Sem - VI/Open Lab/Vivado projects/uart_rx/uart_rx.sim/sim_1/behav/xsim/xsim.dir/tb_uart_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
