set_property PACKAGE_PIN F22 [get_ports a]
set_property PACKAGE_PIN G22 [get_ports b]
set_property IOSTANDARD LVCMOS33 [get_ports c]
set_property IOSTANDARD LVCMOS33 [get_ports b]
set_property IOSTANDARD LVCMOS33 [get_ports a]
set_property DRIVE 12 [get_ports c]
set_property SLEW SLOW [get_ports c]
set_property PACKAGE_PIN T22 [get_ports c]
