set_property SRC_FILE_INFO {cfile:{E:/Aghilan/Amrita/Sem - VI/Open Lab/Vivado projects/and_gate_test/and_gate_test.srcs/constrs_1/new/and_gate.xdc} rfile:../../../and_gate_test.srcs/constrs_1/new/and_gate.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F22 [get_ports a]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G22 [get_ports b]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T22 [get_ports c]
