# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Aghilan/Amrita/Project_phase_2/proj_directory/basic_working_firmware_trojan/basic_working_firmware_trojan.srcs/sources_1/bd/trojan_design/ip/trojan_design_processing_system7_0_0/trojan_design_processing_system7_0_0.xci
# IP: The module: 'trojan_design_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Aghilan/Amrita/Project_phase_2/proj_directory/basic_working_firmware_trojan/basic_working_firmware_trojan.gen/sources_1/bd/trojan_design/ip/trojan_design_processing_system7_0_0/trojan_design_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'trojan_design_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: d:/Aghilan/Amrita/Project_phase_2/proj_directory/basic_working_firmware_trojan/basic_working_firmware_trojan.srcs/sources_1/bd/trojan_design/ip/trojan_design_processing_system7_0_0/trojan_design_processing_system7_0_0.xci
# IP: The module: 'trojan_design_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Aghilan/Amrita/Project_phase_2/proj_directory/basic_working_firmware_trojan/basic_working_firmware_trojan.gen/sources_1/bd/trojan_design/ip/trojan_design_processing_system7_0_0/trojan_design_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'trojan_design_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
