# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/trojan_design/trojan_design.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==trojan_design || ORIG_REF_NAME==trojan_design} -quiet] -quiet

# IP: bd/trojan_design/ip/trojan_design_processing_system7_0_0/trojan_design_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==trojan_design_processing_system7_0_0 || ORIG_REF_NAME==trojan_design_processing_system7_0_0} -quiet] -quiet

# XDC: d:/Aghilan/Amrita/Project_phase_2/proj_directory/basic_working_firmware_trojan/basic_working_firmware_trojan.gen/sources_1/bd/trojan_design/trojan_design_ooc.xdc
