@echo off
REM ****************************************************************************
REM Vivado (TM) v2020.2 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Sun Mar 31 23:51:54 +0530 2024
REM SW Build 3064766 on Wed Nov 18 09:12:45 MST 2020
REM
REM Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
REM elaborate design
echo "xelab -wto d6c33c25e88b4f509b99495aa8a1c23b --incr --debug typical --relax --mt 2 -L secureip --snapshot tb_top_level_module_behav xil_defaultlib.tb_top_level_module -log elaborate.log"
call xelab  -wto d6c33c25e88b4f509b99495aa8a1c23b --incr --debug typical --relax --mt 2 -L secureip --snapshot tb_top_level_module_behav xil_defaultlib.tb_top_level_module -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
